# Generated by Django 5.2.8 on 2025-11-18 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveal_date', models.DateTimeField(help_text='Fecha y hora para revelar los resultados del juego.')),
            ],
            options={
                'verbose_name_plural': 'Configuraciones del Juego',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_receiver', models.TextField()),
                ('giver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_guess', models.TextField()),
                ('target_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_on_me', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'target_giver')},
            },
        ),
    ]
